# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: PacketParker
          template: classic
          base: header
          config_timezone: America/Chicago
          commits_authoring: PacketParker, contact@pkrm.dev, Parker M, Parker M., Parker
          plugin_languages: true
          plugin_languages_limit: 4
          plugin_languages_indepth: true
          plugin_languages_details: lines, bytes-size
          plugin_languages_indepth_custom: packetparker/cs312, packetparker/cs314
